### ISSUE TITLE
Support pretty print of Expr

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/promql-parser#55]
I.e., be able to convert a parsed `Expr` back to PromQL literal. This is useful for debug and implement [format](https://prometheus.io/docs/prometheus/latest/querying/api/#formatting-query-expressions) interface in Prometheus

**Comment by parkma99** [comment]
Hi I'm new to the project and I'd like to have a try with the issue.

**Comment by yuanbohan** [comment]
- [x] https://github.com/prometheus/prometheus/blob/main/promql/parser/printer.go in #69 
- [ ] https://github.com/prometheus/prometheus/blob/main/promql/parser/prettier.go
