### ISSUE TITLE
Add Expr Visitor trait

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/promql-parser#57]
Add `ExprVisitor` like this in [DataFusion's PlanVisitor](https://docs.rs/datafusion-expr/latest/datafusion_expr/trait.PlanVisitor.html):
```rust
pub trait PlanVisitor {
    type Error;

    fn pre_visit(&mut self, plan: &LogicalPlan) -> Result<bool, Self::Error>;

    fn post_visit(&mut self, _plan: &LogicalPlan) -> Result<bool, Self::Error> {
        Ok(true)
    }
}
```
It's a util trait convenient for traversing an `Expr`. Like in this scenario https://github.com/GreptimeTeam/greptimedb/blob/6833b405d95239e4bfd2b000106f5b1ddc94bfac/src/servers/src/promql.rs#L373-L398

**Comment by yuanbohan** [comment]
Yes, it is helpful in many scenarios. Prometheus has its own way to `Walk` the tree
[Visitor](https://github.com/prometheus/prometheus/blob/main/promql/parser/ast.go#L294-L324)
