### ISSUE TITLE
walk_expr does not traverse function arguments

### ISSUE THREAD

**Issue by sjmiller609** [GreptimeTeam/promql-parser#66]
For example this query:

```
(sum by (namespace) (max_over_time(pg_stat_activity_count{}[1h])))
```

the walk looks like

```
walking... Paren(ParenExpr { expr: Aggregate(AggregateExpr { op: TokenType(53), expr: Call(Call { func: Function { name: "max_over_time", arg_types: [Matrix], variadic: false, return_type: Vector }, args: FunctionArgs { args: [MatrixSelector(MatrixSelector { vector_selector: VectorSelector { name: Some("pg_stat_activity_count"), matchers: Matchers { matchers: {Matcher { op: Equal, name: "__name__", value: "pg_stat_activity_count" }} }, offset: None, at: None }, range: 3600s })] } }), param: None, modifier: Some(Include({"namespace"})) }) })
walking... Aggregate(AggregateExpr { op: TokenType(53), expr: Call(Call { func: Function { name: "max_over_time", arg_types: [Matrix], variadic: false, return_type: Vector }, args: FunctionArgs { args: [MatrixSelector(MatrixSelector { vector_selector: VectorSelector { name: Some("pg_stat_activity_count"), matchers: Matchers { matchers: {Matcher { op: Equal, name: "__name__", value: "pg_stat_activity_count" }} }, offset: None, at: None }, range: 3600s })] } }), param: None, modifier: Some(Include({"namespace"})) })
walking... Call(Call { func: Function { name: "max_over_time", arg_types: [Matrix], variadic: false, return_type: Vector }, args: FunctionArgs { args: [MatrixSelector(MatrixSelector { vector_selector: VectorSelector { name: Some("pg_stat_activity_count"), matchers: Matchers { matchers: {Matcher { op: Equal, name: "__name__", value: "pg_stat_activity_count" }} }, offset: None, at: None }, range: 3600s })] } })
```

I believe it misses function arguments in Call. I think it also misses vector selector of a matrix selector.

**Comment by waynexia** [comment]
Thanks for reporting :heart:. We do ignore function arguments in `walk_expr`. Unlike `BinaryExpr` or `ParenExpr`, `FunctionArgs` looks like not in the same level with `CallExpr` -- they are more like `MatrixSelector` and `InstantSelector`, is an interior state to its parent.

But we've reviewed our initial design after you raised this issue, both `Call` and `FunctionArgs` is with type `Expr`. So it does makes sense to make `walk_expr` walk into func args. Are you willing to submit a patch to fix this?

**Comment by waynexia** [comment]
>Ok sure!

Great!

>Should it also traverse into Matrix selector?

For now I prefer not to walk into Matrix selector. For (a) Vector selector is not wrapped in `Expr` but a plain and concrete type, which is easy to access its inner state. (b) We have to wrap the vector selector back into `Expr` for traversing and it seems unnecessary.

Thus for this time we can only walk into Call and leave `NumberLiteral`, `StringLiteral`, `VectorSelector` and `MatrixSelector` unchanged

**Comment by sjmiller609** [comment]
Thanks! https://github.com/GreptimeTeam/promql-parser/pull/67
