### ISSUE TITLE
use nom

### ISSUE THREAD

**Issue by groobyming** [GreptimeTeam/promql-parser#82]
@yuanbohan May I ask if we have considered using nom to rewrite the parsing of promql and sql?

**Comment by groobyming** [comment]
@yuanbohan

**Comment by yuanbohan** [comment]
Thanks for your concern. We have no plans to rewrite it via nom or pest, but if it is difficult to implement new features via grmtools, we will consider new options.

BTW, do you have any advice for the current implementation?

**Comment by groobyming** [comment]
@yuanbohan I have forked this project and made some simple extensions. For example,  modify ast when supporting ast traversal, which means supporting rewrite ast.

**Comment by yuanbohan** [comment]
> @yuanbohan I have forked this project and made some simple extensions. For example, modify ast when supporting ast traversal, which means supporting rewrite ast.

Excellent. I'm expecting appealing features from your nom exploration for promql-parser. Although we have no plan to use nom so far, go ahead for your interest 🚀
